METHOD:
  name_method: 'HARD_EM_DIRICHLET'
  iter: 10
  lambd: 0  
  iter_mm: 1000
  fact_opts: {'oxfordpets': 1.0, 'eurosat': 1.0, 'ucf101': 1.0, 'fgvcaircraft': 1.0, 'food101': 1.6, 'dtd': 1.2, 'caltech101': 1.0, 'flowers102': 1.1, 'stanfordcars': 2.0 }
  #T_opts: {'oxfordpets': 25, 'eurosat': 60, 'ucf101': 25, 'fgvcaircraft': 25, 'food101': 20, 'dtd': 25, 'caltech101': 3, 'flowers102': 25, 'stanfordcars': 15}
  T_opts: {'oxfordpets': 25, 'eurosat': 100, 'ucf101': 25, 'fgvcaircraft': 2, 'food101': 15, 'dtd': 40, 'caltech101': 4, 'flowers102': 20, 'stanfordcars': 30, 'sun397': 30, imagenet': 4}
  fact: 1.0
  acc_clustering: True