METHOD:
  name_method: 'TIM-GD'
  temp: 15
  loss_weights: [1.0, 0.3, 1.0]  # [Xent, H(Y), H(Y|X)]
  lr_tim: 1e-4
  iter: 2000
  alpha: 1.0
  acc_clustering: False
  T_opts: {'oxfordpets': 4, 'eurosat': 100, 'ucf101': 15, 'fgvcaircraft': 25, 'food101': 15, 'dtd': 1, 'caltech101': 10, 'flowers102': 10, 'stanfordcars': 25, 'sun397': 40, 'imagenet': 10}