EVAL:
    dataset: 'food101' # oxfordpets eurosat ucf101 caltech101 dtd fgvcaircraft food101 flowers102 stanfordcars
    method: 'laplacian_shot' # zero-shot: 'em_dirichlet', 'hard_em_dirichlet', 'hard_kmeans' 'kl_kmeans', 'soft_kmeans', 'inductive_clip'
                        # few-shot: 'em_dirichlet', hard_em_dirichlet', 'paddle', 'alpha_tim', 'laplacian_shot', 'bdcspn'
    number_tasks: 5        # Number of tasks to evaluate
    batch_size: 5
    k_eff: 10              # number of different classes represented in the query
    n_query: 75            # number of samples in the query set
    shots: 4              # number of shots
    log_path: '.log/'
    save_results: True
    used_test_set: 'test'   # 'val' or 'test'
    device: 0
    T: 30                    # temperature for defining the features
    backbone: 'RN50'        # CLIP's pretrained backbone
    lambd_opt: True        # keep it to this value, will probably be removed soon
    use_softmax_feature: True