EVAL:
    dataset: 'oxfordpets' # oxfordpets eurosat ucf101 caltech101 dtd fgvcaircraft food101 flowers102 stanfordcars
    method: 'hard_em_dirichlet' #'hard_em_dirichlet', 'hard_kmeans' 'kl_kmeans', 'soft_kmeans', 'inductive_clip'
    number_tasks: 100        # Number of tasks to evaluate
    batch_size: 100
    k_eff: 10                # number of different classes represented in the query
    n_ways : 'full'         # 'full' for all test classes (i.e. K), or integer
    n_query: 75            # number of samples in the query set
    sampling: 'uniform'     # ('balanced' | 'uniform') sampling of the query
    shots: 4              # number of shots
    log_path: '.log/'
    save_results: False
    used_test_set: 'test'   # 'val' or 'test'
    device: 0
    T: 30                    # temperature for defining the features
    backbone: 'RN50'        # CLIP's pretrained backbone
    lambd_opt: False        # keep it to this value, will probably be removed soon
    use_softmax_feature: True