DATA:
    dataset: 'eurosat'
    root: 'data'
    dataset_path: 'data/eurosat/'
    num_classes_train: 10
    num_classes_test: 10
    
DISTRIBUTED:
    cuda: True
    seed: 2020
    log_path: 'logs' # path to where log files will be saved 

