DATA:
    dataset: 'caltech101'
    root: 'data'
    dataset_path: 'data/caltech101/'
    num_classes_train: 100
    num_classes_test: 100
    
DISTRIBUTED:
    cuda: True
    seed: 2020
    log_path: 'logs' # path to where log files will be saved 